Shader "Gongbi/Toon"
{
    Properties
    {
        _MainColor ("Main Color", Color) = (1,1,1,1)
        _ShadowColor ("Shadow Color", Color) = (0.6,0.6,0.6,1)
        _OutlineColor ("Outline Color", Color) = (0.08,0.06,0.04,1)
        _OutlineWidth ("Outline Width", Range(0.0, 0.05)) = 0.012
        _ToonSpecColor ("Specular Color", Color) = (0.9,0.8,0.6,1)
        _ToonSpecPower ("Specular Power", Range(1, 200)) = 64
        _ShadowBand ("Shadow Band Threshold", Range(0.0, 1.0)) = 0.35
        _MidBand ("Mid Band Threshold", Range(0.0, 1.0)) = 0.7
        _ShadowIntensity ("Shadow Intensity", Range(0.0, 1.0)) = 0.55
        _LightTint ("Light Tint Influence", Range(0.0, 1.0)) = 0.25
        _WindSway ("Wind Sway Amount", Range(0.0, 1.0)) = 0.0
        _WindHeightFactor ("Wind Height Factor", Float) = 1.0
    }

    SubShader
    {
        Tags { "RenderType" = "Opaque" "Queue" = "Geometry" }
        LOD 100

        // ── Pass 1: Outline (back-face extrusion) ──
        Pass
        {
            Name "OUTLINE"
            Tags { "LightMode" = "Always" }
            Cull Front
            ZWrite On

            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #include "UnityCG.cginc"

            float _OutlineWidth;
            fixed4 _OutlineColor;
            float _WindSway;
            float _WindHeightFactor;

            // Global wind params (set by WindSystem.cs)
            float _WindSpeed;
            float _WindMagnitude;
            float _WindTurbulence;
            float _WindDirectionX;
            float _WindDirectionZ;
            float _GustDensity;
            float _WindIntensity;

            struct appdata
            {
                float4 vertex : POSITION;
                float3 normal : NORMAL;
            };

            struct v2f
            {
                float4 pos : SV_POSITION;
            };

            // Apply wind displacement to a vertex position
            float3 ApplyWind(float3 worldPos, float localY)
            {
                if (_WindSway <= 0.001) return worldPos;

                // Higher vertices sway more
                float heightFactor = saturate(localY * _WindHeightFactor * 0.15);

                // Primary sway: sinusoidal based on time and height
                float swayPhase = _Time.y * _WindSpeed + localY * _GustDensity * 3.0;
                float sway = sin(swayPhase) * _WindMagnitude * _WindIntensity * _WindSway * heightFactor;

                // Turbulence: secondary noise-like variation
                float turb = sin(swayPhase * _WindTurbulence + worldPos.x * 0.5) * 0.3;
                sway += turb * _WindMagnitude * _WindIntensity * _WindSway * heightFactor;

                // Apply along wind direction
                worldPos.x += _WindDirectionX * sway;
                worldPos.z += _WindDirectionZ * sway;

                return worldPos;
            }

            v2f vert(appdata v)
            {
                v2f o;

                // Apply wind displacement before outline extrusion
                float3 worldPos = mul(unity_ObjectToWorld, v.vertex).xyz;
                worldPos = ApplyWind(worldPos, v.vertex.y);
                float3 viewPos = mul(UNITY_MATRIX_V, float4(worldPos, 1.0)).xyz;

                float3 viewNormal = normalize(mul((float3x3)UNITY_MATRIX_IT_MV, v.normal));
                viewPos += viewNormal * _OutlineWidth;
                o.pos = mul(UNITY_MATRIX_P, float4(viewPos, 1.0));
                return o;
            }

            fixed4 frag(v2f i) : SV_Target
            {
                return _OutlineColor;
            }
            ENDCG
        }

        // ── Pass 2: Cel-shaded surface (ForwardBase + ForwardAdd generated by surface shader) ──
        CGPROGRAM
        #pragma surface surf Cel vertex:vert fullfwdshadows
        #pragma target 3.0

        fixed4 _MainColor;
        fixed4 _ShadowColor;
        fixed4 _ToonSpecColor;
        float  _ToonSpecPower;
        float  _ShadowBand;
        float  _MidBand;
        float  _ShadowIntensity;
        float  _LightTint;
        float  _WindSway;
        float  _WindHeightFactor;

        // Global wind params
        float _WindSpeed;
        float _WindMagnitude;
        float _WindTurbulence;
        float _WindDirectionX;
        float _WindDirectionZ;
        float _GustDensity;
        float _WindIntensity;

        half4 LightingCel(SurfaceOutput s, half3 lightDir, half3 viewDir, half atten)
        {
            half NdotL = dot(s.Normal, lightDir);

            half cel;
            if (NdotL < _ShadowBand)
                cel = 1.0 - _ShadowIntensity;
            else if (NdotL < _MidBand)
                cel = 1.0 - _ShadowIntensity * 0.5;
            else
                cel = 1.0;

            half3 halfVec = normalize(lightDir + viewDir);
            half NdotH = max(dot(s.Normal, halfVec), 0);
            half spec = step(0.5, pow(NdotH, _ToonSpecPower));

            half3 baseColor = lerp(_ShadowColor.rgb, _MainColor.rgb, cel);
            baseColor += spec * _ToonSpecColor.rgb * 0.35;

            baseColor *= lerp(fixed3(1,1,1), _LightColor0.rgb, _LightTint) * (atten * 2);

            return half4(baseColor, s.Alpha);
        }

        struct Input
        {
            float2 uv_MainTex;
        };

        void vert(inout appdata_full v)
        {
            if (_WindSway <= 0.001) return;

            float3 worldPos = mul(unity_ObjectToWorld, v.vertex).xyz;
            float localY = v.vertex.y;

            float heightFactor = saturate(localY * _WindHeightFactor * 0.15);
            float swayPhase = _Time.y * _WindSpeed + localY * _GustDensity * 3.0;
            float sway = sin(swayPhase) * _WindMagnitude * _WindIntensity * _WindSway * heightFactor;

            float turb = sin(swayPhase * _WindTurbulence + worldPos.x * 0.5) * 0.3;
            sway += turb * _WindMagnitude * _WindIntensity * _WindSway * heightFactor;

            worldPos.x += _WindDirectionX * sway;
            worldPos.z += _WindDirectionZ * sway;

            v.vertex = mul(unity_WorldToObject, float4(worldPos, 1.0));
        }

        void surf(Input IN, inout SurfaceOutput o)
        {
            o.Albedo = _MainColor.rgb;
            o.Alpha = _MainColor.a;
        }
        ENDCG
    }

    Fallback "Diffuse"
}
