using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

public static class RemoveDefaultCameras
{
    // Scenes were generated by SceneSetup.CreateXROrigin, which adds the XR rig
    // camera ("MainCamera", child of XROrigin). The Unity default "Main Camera"
    // (root level) was never deleted, so every scene rendered the world twice
    // (two full-scene stereo cameras + two AudioListeners).
    static readonly string[] ScenePaths =
    {
        "Assets/Scenes/00_Start.unity",
        "Assets/Scenes/01_Bamboo.unity",
        "Assets/Scenes/02_Waterfall.unity",
        "Assets/Scenes/03_Pavilion.unity",
        "Assets/Scenes/04_Summit.unity",
        "Assets/Scenes/99_End.unity",
    };

    public static void Run()
    {
        foreach (var path in ScenePaths)
        {
            var scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
            bool removed = false;
            foreach (var go in scene.GetRootGameObjects())
            {
                // Default Unity camera is named "Main Camera" (with space) and
                // sits at the scene root; the XR rig camera is "MainCamera".
                if (go.name == "Main Camera" && go.transform.parent == null)
                {
                    Object.DestroyImmediate(go);
                    removed = true;
                }
            }
            if (removed)
            {
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
                Debug.Log("[RemoveDefaultCameras] Removed default camera: " + path);
            }
            else
            {
                Debug.Log("[RemoveDefaultCameras] No default camera in " + path);
            }
        }
        Debug.Log("[RemoveDefaultCameras] Done");
    }
}
